[[fields]]
name = "cream"
pattern = "(Cream,(.*?),)"
flags = "im"
ordered_groups = [2]
[[fields]]
name = "milk"
pattern = "(Milk solids), (\\w+?),"
flags = "im"
ordered_groups = [2]
group_join_symbol = " - "