file_locations.raw = "data/winemag-data-130k-v2.csv"
file_locations.clean = "data/winemag-data-130k-v2-clean.csv"
data_notes = "data webscraped from kaggle: https://www.kaggle.com/zynicide/wine-reviews"
